services:
  - type: web
    name: pokemon-quick-guide
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_TIMEOUT
        value: "30"
      - key: GUNICORN_MAX_REQUESTS
        value: "1000"
      - key: PYTHONPATH
        value: "/opt/render/project/src" 